#!/usr/bin/env python3
"""
BIS Trust Copilot / MANAK-AI (SIH26107)
Product-to-Standard Taxonomy & Multilingual Resolver Builder

Generates data/bis_catalogue/product_taxonomy.json mapping consumer and industrial
products, synonyms, and Hindi/Hinglish terms directly to authoritative Indian Standards,
QCO mandatory status, certification schemes, and testing requirements.
"""

import os
import json

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_FILE = os.path.join(ROOT_DIR, "data", "bis_catalogue", "product_taxonomy.json")
os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)

TAXONOMY = {
    "products": [
        {
            "id": "prod:two-wheeler-helmet",
            "name": "Two-Wheeler Protective Helmet",
            "aliases": ["helmet", "helmets", "bike helmet", "motorcycle helmet", "protective helmet", "two wheeler helmet", "rider helmet"],
            "hindi_terms": ["helmet", "helmat", "bike ka helmet", "motorcycle helmet", "sir ki suraksha helmet"],
            "standard_code": "IS 4151:2015",
            "base_num": "4151",
            "division": "TED",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Two-Wheeler Helmets (Quality Control) Mandatory Statutory Order",
            "issuing_ministry": "Ministry of Road Transport and Highways (MoRTH)",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Impact Absorption Test (Clause 7.4)", "Retention System Strength Test (Clause 8.2)", "Visor Optical Clarity (Clause 9.1)"],
            "labs": ["BIS Central Laboratory (Sahibabad)", "NABL Accredited Helmet Testing Laboratories"],
            "rationale": "IS 4151:2015 is the mandatory national standard for protective helmets for motorcycle and two-wheeler riders under Central Motor Vehicles Rules (CMVR) and MoRTH QCO."
        },
        {
            "id": "prod:tmt-steel-bars",
            "name": "TMT Rebars / High Strength Deformed Steel Bars",
            "aliases": ["tmt bar", "tmt bars", "tmt sariya", "steel rebar", "reinforcement steel", "construction steel", "fe 500d", "fe 550d", "fe 415", "sariya", "concrete reinforcement wire"],
            "hindi_terms": ["sariya", "tmt sariya", "lohe ka sariya", "makan banane ka sariya", "cement sariya"],
            "standard_code": "IS 1786:2008",
            "base_num": "1786",
            "division": "CED",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Steel and Steel Products (Quality Control) Order",
            "issuing_ministry": "Ministry of Steel",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Tensile Strength & 0.2% Proof Stress (Clause 8.1)", "Carbon & Sulphur Chemical Limits (Clause 4.2)", "Bend and Rebend Test (Clause 9.1)"],
            "labs": ["BIS Central Laboratory", "National Metallurgical Laboratory (NML)", "NABL Accredited Steel Testing Labs"],
            "rationale": "IS 1786:2008 covers high-strength deformed steel bars and wires for concrete reinforcement in building construction."
        },
        {
            "id": "prod:gold-hallmark-jewellery",
            "name": "Gold Artefacts & Jewellery Hallmarking",
            "aliases": ["gold", "gold jewellery", "gold jewelry", "gold ring", "gold chain", "gold hallmark", "huid", "22k gold", "18k gold", "14k gold", "916 gold", "hallmarked gold"],
            "hindi_terms": ["sona", "sone ke gehne", "sona hallmark", "huid number", "sone ki ring", "22 carat sona"],
            "standard_code": "IS 1417:2016",
            "base_num": "1417",
            "division": "MTD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Hallmarking of Gold Jewellery and Artefacts Mandatory Order",
            "issuing_ministry": "Ministry of Consumer Affairs, Food & Public Distribution",
            "scheme": "Scheme-IV (Precious Metals Hallmarking / 6-Digit HUID)",
            "key_tests": ["X-Ray Fluorescence (XRF) Spectrometry (Clause 6.1)", "Fire Assay Cupellation Lead Method (IS 1418)", "6-Digit Alphanumeric HUID Laser Marking"],
            "labs": ["BIS Recognized Assaying and Hallmarking Centres (AHCs)"],
            "rationale": "IS 1417:2016 prescribes gold purity grades (916/22K, 750/18K, 585/14K) and mandatory 6-digit HUID hallmarking."
        },
        {
            "id": "prod:silver-hallmark-jewellery",
            "name": "Silver Artefacts & Jewellery Hallmarking",
            "aliases": ["silver", "silver jewellery", "silver jewelry", "silver hallmark", "chandi", "999 silver", "925 sterling silver"],
            "hindi_terms": ["chandi", "chandi ke bartan", "chandi hallmark", "chandi ki payal"],
            "standard_code": "IS 2112:2014",
            "base_num": "2112",
            "division": "MTD",
            "status": "CURRENT",
            "is_mandatory": False,
            "qco_name": "Silver Hallmarking Voluntary Scheme",
            "issuing_ministry": "Ministry of Consumer Affairs, Food & Public Distribution",
            "scheme": "Scheme-IV (Precious Metals Hallmarking)",
            "key_tests": ["Potentiometric Titration", "XRF Purity Verification"],
            "labs": ["BIS Recognized Assaying and Hallmarking Centres (AHCs)"],
            "rationale": "IS 2112:2014 specifies purity grades for silver alloys and artefacts (999, 970, 925, 900, 835, 800 fineness)."
        },
        {
            "id": "prod:packaged-drinking-water",
            "name": "Packaged Drinking Water (Other than Natural Mineral Water)",
            "aliases": ["packaged drinking water", "water bottle", "bisleri", "packaged water", "mineral water bottle", "bottled water", "water jar", "20l water jar"],
            "hindi_terms": ["paani ki bottle", "bottled paani", "drinking water bottle", "peene ka paani bottle"],
            "standard_code": "IS 14543:2024",
            "base_num": "14543",
            "division": "FAD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Packaged Drinking Water Mandatory Certification Order",
            "issuing_ministry": "Ministry of Consumer Affairs & Food Safety and Standards Authority of India (FSSAI)",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Microbiological Safety - Coliform & E. coli Zero Count (Clause 5.3)", "Total Dissolved Solids TDS 75-500 mg/L (Table 1)", "Pesticide Residue Limits (Table 3)"],
            "labs": ["BIS Central Laboratory", "NABL Accredited Water Testing Labs"],
            "rationale": "IS 14543:2024 is the mandatory standard for packaged drinking water sold in sealed plastic bottles, pouches, and jars."
        },
        {
            "id": "prod:drinking-water-piped",
            "name": "Drinking Water Supply (Tap Water / Municipal Water)",
            "aliases": ["drinking water", "tap water", "municipal water", "potable water", "well water", "borewell water", "jal jeevan mission water"],
            "hindi_terms": ["peene ka paani", "nal ka paani", "drinking water niyam", "jal jeevan water"],
            "standard_code": "IS 10500:2012",
            "base_num": "10500",
            "division": "FAD",
            "status": "CURRENT",
            "is_mandatory": False,
            "qco_name": "Drinking Water National Quality Benchmark",
            "issuing_ministry": "Ministry of Jal Shakti / Bureau of Indian Standards",
            "scheme": "Scheme-I (Product Specification Benchmark)",
            "key_tests": ["pH (6.5 to 8.5)", "TDS max 500 mg/L (permissible up to 2000 mg/L)", "Turbidity max 1 NTU", "Heavy Metals (Lead <= 0.01 mg/L, Arsenic <= 0.01 mg/L)"],
            "labs": ["Public Health Engineering Labs", "BIS Recognized Labs"],
            "rationale": "IS 10500:2012 specifies the essential physical, chemical, and bacteriological quality requirements for potable municipal and domestic drinking water."
        },
        {
            "id": "prod:electric-cables",
            "name": "PVC Insulated Domestic Electric Wires & Cables",
            "aliases": ["electric wire", "electric cables", "pvc cables", "copper wire", "house wire", "wiring cable", "flexible cable", "power cord"],
            "hindi_terms": ["bijli ka taar", "house wiring taar", "copper taar", "pvc cable", "wiring ka taar"],
            "standard_code": "IS 694:2010",
            "base_num": "694",
            "division": "ETD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Electrical Wires and Cables (Quality Control) Order",
            "issuing_ministry": "Department for Promotion of Industry and Internal Trade (DPIIT)",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Conductor Resistance Test (Clause 6.2 / Table 2)", "Insulation Resistance Test (Clause 8.1)", "High Voltage Spark Test (Clause 9.1)", "Flammability Test"],
            "labs": ["Central Power Research Institute (CPRI)", "BIS Central Lab", "NABL Cable Testing Labs"],
            "rationale": "IS 694:2010 covers PVC insulated unsheathed and sheathed cables for working voltages up to and including 1100 V for domestic wiring."
        },
        {
            "id": "prod:pressure-cooker",
            "name": "Domestic Pressure Cooker (Aluminium and Stainless Steel)",
            "aliases": ["pressure cooker", "cooker", "aluminium cooker", "steel pressure cooker", "cooking cooker", "kitchen cooker"],
            "hindi_terms": ["pressure cooker", "cooker", "khana banane ka cooker", "cooker safety niyam"],
            "standard_code": "IS 2347:2017",
            "base_num": "2347",
            "division": "PGD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Domestic Pressure Cooker (Quality Control) Mandatory Order",
            "issuing_ministry": "Department for Promotion of Industry and Internal Trade (DPIIT)",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Hydrostatic Proof Pressure Test (Clause 6.2)", "Bursting Pressure Test >= 300 kPa (Clause 6.3)", "Safety Vent & Fusible Plug Release Pressure Test (Clause 8.1)"],
            "labs": ["BIS Central Laboratory", "NABL Mechanical Testing Labs"],
            "rationale": "IS 2347:2017 specifies safety, manufacturing, and performance requirements for domestic pressure cookers to prevent explosion hazards."
        },
        {
            "id": "prod:electric-geyser",
            "name": "Stationary Storage Electric Water Heaters (Geysers)",
            "aliases": ["geyser", "electric geyser", "water heater", "storage water heater", "instant water heater", "bathroom geyser", "electric water heater"],
            "hindi_terms": ["geyser", "bijli ka geyser", "pani garam karne ka geyser", "water heater"],
            "standard_code": "IS 2082:2018",
            "base_num": "2082",
            "division": "ETD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Electrical Appliances (Quality Control) Order",
            "issuing_ministry": "Department for Promotion of Industry and Internal Trade (DPIIT) / BEE",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Standing Loss Energy Efficiency Test (Clause 14.1 / Table 2)", "Rated Pressure & Hydraulic Test up to 1.0 MPa (Clause 16.2)", "Electrical Leakage Current & Earth Continuity (IS 302-1)"],
            "labs": ["CPRI", "BIS Central Lab", "NABL Electrical Labs"],
            "rationale": "IS 2082:2018 covers safety and performance requirements for stationary electric storage water heaters for domestic use."
        },
        {
            "id": "prod:ceiling-fan",
            "name": "Electric Ceiling Fans and Regulators",
            "aliases": ["ceiling fan", "fan", "electric fan", "bldc fan", "5 star fan", "room fan", "fan regulator"],
            "hindi_terms": ["pankha", "chhat ka pankha", "bldc pankha", "ceiling fan niyam"],
            "standard_code": "IS 374:2019",
            "base_num": "374",
            "division": "ETD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Electric Ceiling Fans (Quality Control) Order",
            "issuing_ministry": "DPIIT / Bureau of Energy Efficiency (BEE)",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Air Delivery Min 210 m3/min (Clause 6.1)", "Service Value Ratio (Clause 6.2)", "Suspension Downrod 1000 N Proof Load Test (Clause 8.2)"],
            "labs": ["BIS Central Laboratory", "NABL Electrical Labs"],
            "rationale": "IS 374:2019 specifies energy efficiency, safety downrod strength, and air delivery for ceiling type electric fans."
        },
        {
            "id": "prod:led-bulb",
            "name": "Self-Ballasted LED Lamps / LED Bulbs",
            "aliases": ["led bulb", "led lamp", "led light", "bulb", "lighting", "b22 led bulb", "e27 led bulb"],
            "hindi_terms": ["led bulb", "led lattu", "bulb", "bijli bulb"],
            "standard_code": "IS 16102 (Part 1):2012",
            "base_num": "16102",
            "division": "ETD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Electronics and IT Goods (Compulsory Registration) Order / MeitY QCO",
            "issuing_ministry": "Ministry of Electronics and Information Technology (MeitY)",
            "scheme": "Scheme-II (Compulsory Registration Scheme - CRS)",
            "key_tests": ["Electric Shock Protection (Clause 6)", "Insulation Resistance & Electric Strength (Clause 7)", "Cap Temperature Rise Test (Clause 12)"],
            "labs": ["ERTL", "ETDC", "BIS/NABL Electronics Labs"],
            "rationale": "IS 16102 (Part 1):2012 covers safety requirements for self-ballasted LED lamps for general lighting services under CRS."
        },
        {
            "id": "prod:toys-children",
            "name": "Safety of Toys for Children",
            "aliases": ["toy", "toys", "children toy", "kids toy", "plastic toy", "electric toy", "stuffed toy", "board game"],
            "hindi_terms": ["khilone", "baccho ke khilone", "plastic khilone", "toy safety niyam"],
            "standard_code": "IS 9873 (Part 1):2019",
            "base_num": "9873",
            "division": "PCD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Toys (Quality Control) Mandatory Order",
            "issuing_ministry": "Department for Promotion of Industry and Internal Trade (DPIIT)",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Small Parts Choking Hazard Gauge Test (Clause 5.1)", "Sharp Edges and Points Test (Clause 5.7)", "Drop and Impact Test for Children under 36 Months (Clause 5.24)"],
            "labs": ["BIS Central Lab", "NABL Accredited Toy Testing Labs"],
            "rationale": "IS 9873 (Part 1):2019 governs mechanical and physical safety aspects of children's toys to prevent choking and laceration risks."
        },
        {
            "id": "prod:footwear-leather-rubber",
            "name": "Footwear Made from Leather, Rubber and Polymeric Materials",
            "aliases": ["footwear", "shoes", "leather shoes", "sports shoes", "safety shoes", "chappal", "sandals", "boots"],
            "hindi_terms": ["joota", "joote", "chappal", "leather joota", "safety joota"],
            "standard_code": "IS 15844 (Part 1):2023",
            "base_num": "15844",
            "division": "CHD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Footwear made from Leather and other Materials (Quality Control) Order",
            "issuing_ministry": "Department for Promotion of Industry and Internal Trade (DPIIT)",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Upper-to-Sole Bond Adhesion Strength (Clause 5.2)", "Flexing Resistance of Outsole (Clause 5.4)", "Abrasion Resistance Test (Clause 5.6)"],
            "labs": ["FDDI Labs", "CLRI Chennai", "BIS Recognized Footwear Testing Labs"],
            "rationale": "IS 15844 (Part 1):2023 specifies safety, durability, and material performance requirements for sports and general footwear."
        },
        {
            "id": "prod:stainless-steel-water-bottle",
            "name": "Stainless Steel Vacuum Flasks & Insulated Water Bottles",
            "aliases": ["steel bottle", "steel water bottle", "insulated bottle", "vacuum flask", "thermos flask", "stainless steel bottle", "milton bottle"],
            "hindi_terms": ["steel ki bottle", "pani ki steel bottle", "thermos", "steel flask"],
            "standard_code": "IS 17526:2021",
            "base_num": "17526",
            "division": "PGD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Cookware and Utensils (Quality Control) Order",
            "issuing_ministry": "Department for Promotion of Industry and Internal Trade (DPIIT)",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Thermal Insulation Performance Test (Clause 6.2)", "Food Grade Stainless Steel Chemical Limits SS 304 (Clause 4.1)", "Leakage Test (Clause 6.5)"],
            "labs": ["BIS Central Laboratory", "NABL Mechanical Labs"],
            "rationale": "IS 17526:2021 prescribes quality, food-contact grade stainless steel alloy, and temperature retention for stainless steel vacuum flasks."
        },
        {
            "id": "prod:lpg-cylinder",
            "name": "Welded Low Carbon Steel Cylinders for LPG",
            "aliases": ["lpg cylinder", "gas cylinder", "cooking gas cylinder", "indane cylinder", "hp gas cylinder", "bharat gas cylinder", "14.2kg cylinder"],
            "hindi_terms": ["gas cylinder", "lpg cylinder", "rasoi gas cylinder", "cylinder niyam"],
            "standard_code": "IS 3196 (Part 1):2006",
            "base_num": "3196",
            "division": "PGD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Gas Cylinders Rules / PESO & Statutory Mandatory Order",
            "issuing_ministry": "Ministry of Petroleum and Natural Gas (MoPNG) / PESO",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Hydrostatic Test Pressure 2.50 MPa (Clause 9.1)", "Volumetric Expansion Test (Clause 9.2)", "Bursting Pressure Test >= 4.50 MPa (Clause 9.3)"],
            "labs": ["BIS Central Lab", "PESO Approved Cylinder Testing Stations"],
            "rationale": "IS 3196 (Part 1):2006 governs manufacturing, welding, safety valves, and pressure tests for LPG cooking gas cylinders."
        },
        {
            "id": "prod:cement-opc-ppc",
            "name": "Ordinary Portland Cement (OPC) & Portland Pozzolana Cement (PPC)",
            "aliases": ["cement", "opc cement", "ppc cement", "opc 53", "opc 43", "ultratech cement", "amvbuja cement", "construction cement"],
            "hindi_terms": ["cement", "simint", "makan ka cement", "cement niyam"],
            "standard_code": "IS 269:2015",
            "base_num": "269",
            "division": "CED",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Cement (Quality Control) Mandatory Order",
            "issuing_ministry": "Department for Promotion of Industry and Internal Trade (DPIIT)",
            "scheme": "Scheme-I (ISI Mark Product Certification)",
            "key_tests": ["Compressive Strength 28-Day Test (Clause 6.2)", "Soundness Le-Chatelier Expansion <= 10mm (Clause 6.1)", "Initial Setting Time >= 30 mins (Clause 6.1)"],
            "labs": ["National Council for Cement and Building Materials (NCCBM)", "BIS Central Lab"],
            "rationale": "IS 269:2015 covers chemical and physical requirements for Ordinary Portland Cement across 33, 43, and 53 grades."
        },
        {
            "id": "prod:concrete-design",
            "name": "Plain and Reinforced Concrete Code of Practice",
            "aliases": ["concrete", "rcc", "reinforced concrete", "concrete mix", "m20 concrete", "m25 concrete", "slab concrete", "column concrete"],
            "hindi_terms": ["concrete", "chhat ki concrete", "rcc slab", "concrete mix niyam"],
            "standard_code": "IS 456:2000",
            "base_num": "456",
            "division": "CED",
            "status": "CURRENT",
            "is_mandatory": False,
            "qco_name": "National Building Code of India (NBC) Primary Code",
            "issuing_ministry": "Bureau of Indian Standards",
            "scheme": "Scheme-I (Code of Practice Benchmark)",
            "key_tests": ["28-Day Cube Compressive Strength fck (Clause 6.1)", "Minimum Cover to Rebars for Durability (Table 16)", "Max Water-Cement Ratio (Table 5)"],
            "labs": ["Civil Engineering Testing Labs", "NCCBM", "BIS Recognized Labs"],
            "rationale": "IS 456:2000 is the national building code governing design and construction of plain and reinforced concrete structures in India."
        },
        {
            "id": "prod:li-ion-battery",
            "name": "Secondary Lithium-ion Cells & Batteries for Portable Applications",
            "aliases": ["lithium battery", "li-ion battery", "phone battery", "laptop battery", "power bank battery", "portable battery"],
            "hindi_terms": ["mobile battery", "laptop battery", "lithium battery", "power bank"],
            "standard_code": "IS 16046 (Part 2):2018",
            "base_num": "16046",
            "division": "LITD",
            "status": "CURRENT",
            "is_mandatory": True,
            "qco_name": "Electronics and Information Technology Goods (Compulsory Registration) Order",
            "issuing_ministry": "Ministry of Electronics and Information Technology (MeitY)",
            "scheme": "Scheme-II (Compulsory Registration Scheme - CRS)",
            "key_tests": ["Continuous Charging at Constant Voltage (Clause 7.2.1)", "External Short Circuit Test (Clause 7.3.2)", "Thermal Abuse Test 130 deg C (Clause 7.3.4)", "Free Fall Drop Test (Clause 7.3.3)"],
            "labs": ["ERTL", "ETDC", "TUV/UL BIS Recognized Labs"],
            "rationale": "IS 16046 (Part 2):2018 (equivalent to IEC 62133-2) specifies safety tests against thermal runaway, short circuit, and explosion for portable Li-ion batteries under CRS."
        }
    ]
}

with open(OUT_FILE, "w", encoding="utf-8") as f:
    json.dump(TAXONOMY, f, indent=2, ensure_ascii=False)

print(f"✅ Generated Product Taxonomy with {len(TAXONOMY['products'])} product entries at: {OUT_FILE}")
